name: pokeapi_app
description: "A new Flutter project for PokeAPI with Riverpod and Dio."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.0.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/pokemon_placeholder.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
